-- AI Insight Feedback table and RLS

create table if not exists public.ai_insight_feedback (
  id bigint generated by default as identity primary key,
  insight_id text,
  user_id uuid references auth.users(id) on delete cascade,
  vote text check (vote in ('up','down')) not null,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

alter table if exists public.ai_insight_feedback enable row level security;

drop policy if exists ai_insight_feedback_self_access on public.ai_insight_feedback;
create policy ai_insight_feedback_self_access on public.ai_insight_feedback
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

